<?php
/**
 * Graph template
 *
 * @category PagespeedAnalysis
 * @package  Monogo|PagespeedAnalysis
 * @author   Paweł Detka <pawel.detka@monogo.pl>
 */
?>
<?php
use Monogo\PagespeedAnalysis\Api\Data\ConfigInterface;
/**
 * @var $block \Monogo\PagespeedAnalysis\Block\Adminhtml\Pagespeed\Graph
 */
?>

<?php
$graphData = $block->getChartData();
?>

<?php if (!$graphData): ?>
    <?= __('Empty chart data. Please configure module and run script.') ?>
<?php else: ?>
    <?php $tabs = $block->getChildBlock('pagespeed_tabs')->setData(ConfigInterface::GRAPH, $graphData); ?>
    <?= $tabs->toHtml(); ?>

    <?php $tabContent = $block->getChildBlock('pagespeed_tab_content')->setData(ConfigInterface::GRAPH, $graphData); ?>
    <?= $tabContent->toHtml(); ?>

    <?php $chartScript = $block->getChildBlock('pagespeed_chart_script')->setData(ConfigInterface::GRAPH, $graphData); ?>
    <?= $chartScript->toHtml(); ?>

    <?php $tabScript = $block->getChildBlock('pagespeed_tab_script')->setData(ConfigInterface::GRAPH, $graphData); ?>
    <?= $tabScript->toHtml(); ?>
<?php endif; ?>


