<?php
/**
 * Graph template
 *
 * @category PagespeedAnalysis
 * @package  Monogo|PagespeedAnalysis
 * @author   Paweł Detka <pawel.detka@monogo.pl>
 */
?>
<?php
/**
 * @var $block \Monogo\PagespeedAnalysis\Block\Adminhtml\Pagespeed\Graph\TabContent
 */
?>

<?php
$graphData = $this->getData(\Monogo\PagespeedAnalysis\Api\Data\ConfigInterface::GRAPH);
?>

<?php foreach ($graphData as $key => $item): ?>
    <?php if (!empty($item)): ?>
        <div id="<?= md5($key) ?>" class="tabcontent">
            <?php $defaultTab = md5($key) ?>
            <?php foreach ($item as $strategy => $data): ?>
                <?php $lastRecord = $block->getLastRecord(base64_decode($key), $strategy); ?>
                <h3><?= strtoupper($strategy) ?> (<?= __('Last') . ' ' . $block->getChartHistory() . ' ' . __('days') ?>
                    )</h3>
                <button id="show_details-<?= $strategy ?>-<?= str_replace('=', '', $key) ?>"
                        title="<?= __('Show details') ?>" type="button"
                        class="action-secondary scalable save ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only <?= md5($key . $strategy) ?>">
                    <span class="ui-button-text">
                        <span><?= __('Show details') ?></span>
                    </span>
                </button>

                <div id="messages-<?= md5($key . $strategy) ?>" style="display: none">
                    <div class="message">

                        <?php if (!empty($lastRecord->getComment())): ?>
                            <?= __('Comment') ?>: <strong><?= $lastRecord->getComment() ?></strong><br/>
                        <?php endif ?>

                        <strong><?= __('Performance') ?></strong>:
                        <span style="font-weight:bold ;color:  <?= $block->getScoreColor($lastRecord->getPerformanceScore()) ?> ">
                            <?= $lastRecord->getPerformanceScore() * 100 ?>%
                        </span>
                        <br/>
                        <strong><?= __('SEO') ?></strong>: <span
                                style="font-weight:bold ;color:  <?= $block->getScoreColor($lastRecord->getSeoScore()) ?> ">
                            <?= $lastRecord->getSeoScore() * 100 ?>%
                        </span>
                        <br/>
                        <strong><?= __('PWA') ?></strong>:
                        <span style="font-weight:bold ;color:  <?= $block->getScoreColor($lastRecord->getPwaScore()) ?> ">
                            <?= $lastRecord->getPwaScore() * 100 ?>%
                        </span>
                        <br/>
                        <strong><?= __('Best Practices') ?></strong>:
                        <span style="font-weight:bold ;color:  <?= $block->getScoreColor($lastRecord->getBestPracticesScore()) ?> ">
                            <?= $lastRecord->getBestPracticesScore() * 100 ?>%
                        </span>
                        <br/>
                        <strong> <?= __('Accessibility') ?></strong>:
                        <span style="font-weight:bold ;color:  <?= $block->getScoreColor($lastRecord->getAccessibilityScore()) ?> ">
                            <?= $lastRecord->getAccessibilityScore() * 100 ?>%
                        </span>
                        <br/>
                        <strong><?= __('TTFB') ?></strong>: <?= $lastRecord->getTtfb() ?>ms<br/>
                        <br/>


                        <?php $renderBlockingResources = json_decode($lastRecord->getRenderBlockingResources(), true) ?>
                        <?php if (!empty($renderBlockingResources)): ?>
                            <strong><?= __('Render Blocking Resources') ?> (<?= count($renderBlockingResources) ?>):</strong><br/>
                            <?php foreach ($renderBlockingResources as $resource): ?>
                                <?= __('URL') ?> : <?= $resource['url'] ?><br/>
                                <?= __('Time') ?> : <?= $resource['wastedMs'] ?>ms<br/>
                                <?= __('Size') ?> : <?= round($resource['totalBytes'] / 1024, 2) ?>kb<br/>
                                <hr/>
                            <?php endforeach; ?>
                            <br/>
                        <?php endif ?>
                        <?php $networkRequests = json_decode($lastRecord->getNetworkRequests(), true) ?>
                        <?php if (!empty($networkRequests)): ?>

                            <strong><?= __('Network Requests') ?> (<?= count($networkRequests) ?>):</strong><br/>
                            <?php foreach ($networkRequests as $requests): ?>
                                <?= __('URL') ?> : <?= $requests['url'] ?><br/>
                                <?= __('Time') ?> : <?= floor($requests['time']) ?>ms<br/>
                                <?= __('Size') ?> : <?= round($requests['resourceSize'] / 1024, 2) ?>kb<br/>
                                <hr/>


                            <?php endforeach; ?>
                        <?php endif ?>

                    </div>
                </div>
                <script type="text/javascript">// <![CDATA[
                    require([
                            'jquery',
                            'Magento_Ui/js/modal/alert'
                        ],
                        function ($, alert) {
                            $('body').on('click', 'button.<?= md5($key . $strategy) ?>', function (event) {
                                alert({
                                    innerScroll: true,
                                    title: '<?= $lastRecord->getUrl() ?><br/>Strategy: <?= $lastRecord->getMode() ?><br/>Date: <?= $lastRecord->getCreatedAt() ?>',
                                    content: $('#messages-<?= md5($key . $strategy) ?>').html()
                                })
                            })
                        }
                    );
                    // ]]></script>

            <?php $urlFilename = $this->getFilenameFromKey($key); ?>
                <div class="wrapper" style="width: 100%; border: #cfcfcf 1px solid; margin-bottom: 20px">
                    <div id="left" style="float: left; width: 50%;">
                        <button onclick="downloadChart('main-<?= $strategy ?>-<?= str_replace('=', '', $key) ?>','<?= $urlFilename.'-score-'.$strategy.'-'.date('Y-m-d_H-i-s') ?>')">
                            <span style="font-size: x-small"><?= __('save chart as image') ?></span>
                        </button>
                        <canvas id="main-<?= $strategy ?>-<?= str_replace('=', '', $key) ?>"
                                height="<?= $block->getChartHeight() ?>px" style="background: #f8f8f8"></canvas>
                    </div>
                    <div id="right" style="float: right; width: 50%;">
                        <button onclick="downloadChart('ttfb-<?= $strategy ?>-<?= str_replace('=', '', $key) ?>','<?= $urlFilename.'-ttfb-'.$strategy.'-'.date('Y-m-d_H-i-s') ?>')">
                            <span style="font-size: x-small"><?= __('save chart as image') ?></span>
                        </button>
                        <canvas id="ttfb-<?= $strategy ?>-<?= str_replace('=', '', $key) ?>"
                                height="<?= $block->getChartHeight() ?>px" style="background: #f8f8f8"></canvas>
                    </div>
                    <div style="clear: both;"></div>
                </div>
            <?php endforeach; ?>
        </div>

    <?php endif; ?>
<?php endforeach; ?>
