<?php
/**
 * Graph template
 *
 * @category PagespeedAnalysis
 * @package  Monogo|PagespeedAnalysis
 * @author   Paweł Detka <pawel.detka@monogo.pl>
 */
?>
<?php
/**
 * @var $block \Monogo\PagespeedAnalysis\Block\Adminhtml\Pagespeed\Graph/Tabs
 */
?>

<?php
$graphData = $this->getData(\Monogo\PagespeedAnalysis\Api\Data\ConfigInterface::GRAPH);
?>

<?php $defaultTab = 'defaultOpen' ?>
<div class="tab">
    <?php foreach ($graphData as $key => $item): ?>
        <?php if (!empty($item)): ?>
            <button class="tablinks" id="tab-<?= $defaultTab ?>"
                    onclick="openTab(event, '<?= md5($key) ?>')"><?= base64_decode($key) ?></button>
            <?php $defaultTab = md5($key) ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
